source 'http://rubygems.org'
ruby '3.0.0'
gem 'sinatra'
gem 'activerecord', :require => 'active_record'
gem 'sinatra-activerecord', :require => 'sinatra/activerecord'
gem 'rake'
gem 'require_all'

gem 'thin'
gem 'shotgun'
gem 'pry'
gem 'bcrypt'
gem "tux" 